import { Download } from "lucide-react";
import jsPDF from "jspdf";

export default function PDFExport({ data }) {
  const generatePDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    let y = 20;

    // Title
    doc.setFontSize(22);
    doc.setTextColor(41, 98, 255);
    doc.text("SOC 2 Compliance Report", pageWidth / 2, y, { align: "center" });
    y += 10;

    doc.setFontSize(14);
    doc.setTextColor(100);
    doc.text(data.company_name, pageWidth / 2, y, { align: "center" });
    y += 15;

    // Score
    doc.setFontSize(16);
    doc.setTextColor(0);
    doc.text(`Compliance Score: ${data.score}%`, 20, y);
    y += 8;
    doc.setFontSize(11);
    doc.setTextColor(100);
    doc.text(`${data.passed} of ${data.total} controls passed`, 20, y);
    y += 15;

    // Separator
    doc.setDrawColor(200);
    doc.line(20, y, pageWidth - 20, y);
    y += 10;

    // Controls
    data.results.forEach((control) => {
      if (y > 260) {
        doc.addPage();
        y = 20;
      }

      // Control header
      doc.setFontSize(12);
      doc.setTextColor(0);
      const status = control.passed ? "[PASS]" : "[FAIL]";
      const severity = control.severity ? ` (${control.severity})` : "";
      doc.text(`${status} ${control.id} - ${control.title}${severity}`, 20, y);
      y += 6;

      doc.setFontSize(9);
      doc.setTextColor(100);
      doc.text(control.description, 25, y);
      y += 6;

      if (!control.passed && control.issues.length > 0) {
        control.issues.forEach((issue) => {
          if (y > 270) {
            doc.addPage();
            y = 20;
          }
          doc.setTextColor(180, 50, 50);
          const lines = doc.splitTextToSize(`- ${issue}`, pageWidth - 50);
          doc.text(lines, 30, y);
          y += lines.length * 5;
        });

        if (control.fix_steps?.length > 0) {
          y += 2;
          doc.setTextColor(50, 100, 180);
          doc.text("Fix Steps:", 30, y);
          y += 5;
          control.fix_steps.forEach((step, i) => {
            if (y > 270) {
              doc.addPage();
              y = 20;
            }
            doc.setTextColor(80);
            const lines = doc.splitTextToSize(`${i + 1}. ${step}`, pageWidth - 55);
            doc.text(lines, 35, y);
            y += lines.length * 5;
          });
        }
      }

      y += 8;
    });

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
      `Generated by SOC2 Analyzer on ${new Date().toLocaleDateString()}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: "center" }
    );

    doc.save(`${data.company_name.replace(/\s+/g, '_')}_SOC2_Report.pdf`);
  };

  return (
    <button
      onClick={generatePDF}
      className="px-5 py-2.5 bg-green-600 hover:bg-green-500 rounded-lg font-semibold transition-all flex items-center gap-2"
    >
      <Download className="w-4 h-4" />
      Export PDF Report
    </button>
  );
}
